version: '3'
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=owasp
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
    restart: always

  dvwa-app:
    build: .
    ports:
      - "80:80"
    environment:
      - DBMS=MySQL
      - DB_SERVER=db
      - DB_USER=dvwa
      - DB_PASSWORD=dvwa
      - DB_DATABASE=dvwa
    depends_on:
      - db
    restart: always